spring:
  datasource:
    url: jdbc:mysql://xxxxxxxx:3306/blog
    username: xxxxxxxxxx
    password: xxxxxxx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    com.lxl.myblog: debug
  file:
    name: log/blog.blog

comment.avatar: https://picsum.photos/seed/picsum/100/100?image=1805